---
# tasks file for mkswap
- name: Create swapfile
  command: fallocate -l 4G /swapfile
  args:
    creates: /swapfile
- name: chmod swapfile
  command: chmod 600 /swapfile
- name: Initialize swapfile 
  command: mkswap /swapfile && touch /.swapfile.created
  args:
    creates: /.swapfile.created
- name: start swapping now
  command: swapon /swapfile && /.swapfile.swapon
  args:
    creates: /.swapfile.swapon
- name: make swap permanent
  lineinfile: dest=/etc/fstab line='/swapfile none swap sw 0 0'
- name: improve swappiness
  command: sysctl vm.swappiness=10
- name: save swappiness
  lineinfile: dest=/etc/sysctl.conf line='vm.swappiness=10'